export enum ScalarFunctionType {
  ToYear = 'to_year',
  ToQuarter = 'to_quarter',
  ToMonth = 'to_month',
  ToDayOfYear = 'to_day_of_year',
  ToDayOfMonth = 'to_day_of_month',
  ToDayOfWeek = 'to_day_of_week',
  ToHour = 'to_hour',
  ToMinute = 'to_minute',
  ToSecond = 'to_second',
  ToYearNum = 'to_year_num',
  ToQuarterNum = 'to_quarter_num',
  ToMonthNum = 'to_month_num',
  ToWeekNum = 'to_week_num',
  ToDayNum = 'to_day_num',
  ToHourNum = 'to_hour_num',
  ToMinuteNum = 'to_minute_num',
  ToSecondNum = 'to_second_num',
  GetArrayElement = 'get_array_element'
}
